USER_ROLE_ADMIN = "admin"
USER_ROLE_USER = "user"

ALLOWED_USER_ROLES = frozenset({USER_ROLE_ADMIN, USER_ROLE_USER})

USER_STATUS_ACTIVE = "active"
USER_STATUS_DISABLED = "disabled"
USER_STATUS_LOCKED = "locked"
USER_STATUS_DELETED = "deleted"

ALLOWED_USER_STATUSES = frozenset(
    {
        USER_STATUS_ACTIVE,
        USER_STATUS_DISABLED,
        USER_STATUS_LOCKED,
        USER_STATUS_DELETED,
    }
)
